site_name: NJIT HPC
site_url: https://arcs-njit-edu.github.io/Docs/
repo_url: https://github.com/arcs-njit-edu/Docs
repo_name: arcs-njit-edu/Docs
nav:
    - Home: index.md
    - Clusters:
      - 'Wulver': 'clusters/wulver.md'
      - 'Lochness': 'clusters/lochness.md'
      - 'Stheno': 'clusters/stheno.md'
      - 'User access to clusters': 'clusters/cluster_access.md'
    - 'Policies': 
      - 'Lochness user policies': 'Policies/lochness_policies.md'
      - 'Wulver usage and Condo policies': 'Policies/wulver_policies.md'
    - 'Facilities': 'facilities/facilities.md'
    - Software:
      - 'Matlab': 'Softwares/matlab.md'
theme: 
  name: material
  logo: img/njit_logo.jpeg
  favicon: favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: rgb(204,0,0)
      accent: rgb(204,0,0)
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
extra_css:
    - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arcs-njit-edu/Docs
    - icon: fontawesome/solid/paper-plane
      link: mailto:hpc@njit.edu
# Extensions
markdown_extensions:
  - meta
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

