site_name: NJIT HPC Documentation
site_url: https://arcs-njit-edu.github.io/Docs/
repo_url: https://github.com/arcs-njit-edu/Docs
#repo_name: arcs-njit-edu/Docs

nav:
    - NJIT HPC: index.md
    - 'About Us':
      - 'about/index.md'
      - 'Contact Us': 'about/contact.md'
    - Clusters:
      - 'clusters/index.md'
      - 'Wulver': 'clusters/wulver.md'
      - 'Decommissioned':
        - 'Stheno': 'clusters/decommissioned/stheno.md'
        - 'Lochness': 'clusters/decommissioned/lochness.md'
      - 'User access to clusters': 'clusters/cluster_access.md'
      - 'Getting started on Wulver': 'clusters/get_started_on_Wulver.md'
      - 'Wulver Filesystems': 'clusters/Wulver_filesystems.md'
    - 'Policies':
      - 'Policies/index.md'
      - 'Wulver policies': 'Policies/wulver_policies.md'
      - 'Condo policies': 'Policies/condo_policies.md'
    - 'Facilities': 'facilities/facilities.md'
    - 'Services': 'Services/hpc-course.md'
    - Status (on-campus or VPN):
        - 'Current Load': 'https://hpc.njit.edu/Monitor/load.html'
        - 'Usage Summary': 'https://hpc.njit.edu/Monitor/summary.html'
        - 'Usage (this year so far)': 'https://hpc.njit.edu/Monitor/cy2025.html'
    - HPC Events and Workshops :
        - Calendar:
            - HPC_Events_and_Workshops/Calendar/index.md
            - 2025 : HPC_Events_and_Workshops/Calendar/2025/
            - 2024 : HPC_Events_and_Workshops/Calendar/2024/
            - Archived : HPC_Events_and_Workshops/Calendar/past_workshops.md
        - Workshop and Training Videos : HPC_Events_and_Workshops/Workshop_and_Training_Videos/
    - Software : Software/
    - Running Jobs: 
        - Overview : Running_jobs/index.md
        - Job Limitations: Running_jobs/job_limitation.md
        - Nodes and Memory: Running_jobs/node-memory-config.md
        - Service Units (SU): Running_jobs/service-units.md
        - Batch Jobs: Running_jobs/batch-jobs.md
        - Interactive Jobs: Running_jobs/interactive-jobs.md
        - Array Jobs: Running_jobs/array-jobs.md
        - Dependency Jobs: Running_jobs/dependency-jobs.md
        - Checkpointing: Running_jobs/checkpointing.md
        - Managing and Monitoring Jobs: Running_jobs/managing-jobs.md
        - Jobs on Ondemand: Running_jobs/ondemand-jobs.md
    - OnDemand :
        - OnDemand Overview: OnDemand/index.md
        - Interactive Apps: OnDemand/Interactive_Apps/
        - 'Files': 'OnDemand/2_files.md'
        - 'Clusters': 'OnDemand/3_clusters.md'
        - 'Tools': 'OnDemand/4_tools.md'
        - 'My Interactive Sessions': 'OnDemand/5_My_Interactive_Sessions.md'
        - 'Jobs': 'OnDemand/6_jobs.md'
    - 'FAQs' : 'faq/faq.md'
    - News : news/index.md
    - '' : 'website_version.txt'
    - '' : 'migration/index.md'
    - '' : 'migration/faqs.md'
    - '' : 'migration/lochness_filesystem.md'
    - '' : 'migration/Lochness_node_owners.md'
    - '' : 'archived/lochness_policies.md'


theme: 
  name: material
  logo: img/Logo_NJIT.png
  custom_dir: overrides
  favicon: favicon.ico
  palette:

    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
    #  toggle:
    #    icon: material/brightness-auto
    #   name: Switch to light mode

    # Palette toggle for light mode
    #- media: "(prefers-color-scheme: light)"
    scheme: njit
     # toggle:
     #   icon: material/toggle-switch
     #   name: Switch to dark mode

    # Palette toggle for dark mode
    #- media: "(prefers-color-scheme: dark)"
    #  scheme: slate
    #  toggle:
    #    icon: material/toggle-switch-off-outline
    #    name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    #- navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
    - content.tooltips
    - header.autohide

extra_css:
    - stylesheets/extra.css
extra:
  social:
    - icon: material/help-box-multiple
      link: https://nexus.njit.edu/highlander_nexus?id=sc_cat_item&sys_id=3f1dd0320a0a0b99000a53f7604a2ef9
      name: Contact HPC support
    - icon: fontawesome/solid/paper-plane
      link: mailto:hpc@njit.edu
      name: Email HPC support
    - icon: material/web
      link: https://ondemand.njit.edu
      name: Open OnDemand
    - icon: material/chart-areaspline
      link: https://hpc.njit.edu/Monitor/summary.html
      name: HPC job metrics

# Extensions
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - markdown-exec
  - table-reader
  - mkdocstrings
  - awesome-pages
  - literate-nav
  - autolinks
  - blog:
      blog_dir: news
      #authors: false
      #archive: false
  - tags

copyright: New Jersey Institute of Technology High Performance Computing